<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2016/07/18 00:29:49

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=222',
  'username' => 'root',
  'password' => 'root',
  'name' => 'doctrine',
)),);
