<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2016/07/17 17:11:23

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=reverse_geocoding',
  'username' => 'root',
  'password' => 'root',
  'name' => 'doctrine',
)),);
