<?php
// auto-generated by sfAutoloadConfigHandler
// date: 2016/07/17 19:23:26
return array(

  // TokenAuthPlugin_module_libs

  // TokenAuthPlugin_lib
  'pluginuserform' => '/var/www/reverse_geocoding.dev/plugins/TokenAuthPlugin/lib/form/doctrine/PluginUserForm.class.php',
  'pluginhistoryform' => '/var/www/reverse_geocoding.dev/plugins/TokenAuthPlugin/lib/form/doctrine/PluginHistoryForm.class.php',
  'pluginuserformfilter' => '/var/www/reverse_geocoding.dev/plugins/TokenAuthPlugin/lib/filter/doctrine/PluginUserFormFilter.class.php',
  'pluginhistoryformfilter' => '/var/www/reverse_geocoding.dev/plugins/TokenAuthPlugin/lib/filter/doctrine/PluginHistoryFormFilter.class.php',
  'tokensecurityuser' => '/var/www/reverse_geocoding.dev/plugins/TokenAuthPlugin/lib/user/tokenSecurityUser.class.php',
  'pluginhistorytable' => '/var/www/reverse_geocoding.dev/plugins/TokenAuthPlugin/lib/model/doctrine/PluginHistoryTable.class.php',
  'pluginuser' => '/var/www/reverse_geocoding.dev/plugins/TokenAuthPlugin/lib/model/doctrine/PluginUser.class.php',
  'pluginhistory' => '/var/www/reverse_geocoding.dev/plugins/TokenAuthPlugin/lib/model/doctrine/PluginHistory.class.php',
  'pluginusertable' => '/var/www/reverse_geocoding.dev/plugins/TokenAuthPlugin/lib/model/doctrine/PluginUserTable.class.php',

  // sfDoctrinePlugin_module_libs

  // sfDoctrinePlugin_lib
  'sfdoctrineconnectionlistener' => '/var/www/reverse_geocoding.dev/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionListener.class.php',
  'sfdoctrineconnectionprofiler' => '/var/www/reverse_geocoding.dev/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionProfiler.class.php',
  'sfdoctrinedatabase' => '/var/www/reverse_geocoding.dev/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineDatabase.class.php',
  'sfdoctrinegeneratemoduletask' => '/var/www/reverse_geocoding.dev/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleTask.class.php',
  'sfdoctrinebuildsqltask' => '/var/www/reverse_geocoding.dev/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSqlTask.class.php',
  'sfdoctrinecleanmodelfilestask' => '/var/www/reverse_geocoding.dev/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCleanModelFilesTask.class.php',
  'sfdoctrineinsertsqltask' => '/var/www/reverse_geocoding.dev/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineInsertSqlTask.class.php',
  'sfdoctrineconfiguredatabasetask' => '/var/www/reverse_geocoding.dev/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineConfigureDatabaseTask.class.php',
  'sfdoctrinedqltask' => '/var/www/reverse_geocoding.dev/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDqlTask.class.php',
  'sfdoctrinebuildschematask' => '/var/www/reverse_geocoding.dev/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSchemaTask.class.php',
  'sfdoctrinebuildtask' => '/var/www/reverse_geocoding.dev/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildTask.class.php',
  'sfdoctrinecreatemodeltables' => '/var/www/reverse_geocoding.dev/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCreateModelTablesTask.class.php',
  'sfdoctrinegeneratemigrationsdbtask' => '/var/www/reverse_geocoding.dev/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDbTask.class.php',
  'sfdoctrinebasetask' => '/var/www/reverse_geocoding.dev/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBaseTask.class.php',
  'sfdoctrinebuildformstask' => '/var/www/reverse_geocoding.dev/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFormsTask.class.php',
  'sfdoctrinegeneratemigrationtask' => '/var/www/reverse_geocoding.dev/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationTask.class.php',
  'sfdoctrinedeletemodelfilestask' => '/var/www/reverse_geocoding.dev/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDeleteModelFilesTask.class.php',
  'sfdoctrinebuildfilterstask' => '/var/www/reverse_geocoding.dev/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFiltersTask.class.php',
  'sfdoctrinemigratetask' => '/var/www/reverse_geocoding.dev/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineMigrateTask.class.php',
  'sfdoctrinegeneratemigrationsdifftask' => '/var/www/reverse_geocoding.dev/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDiffTask.class.php',
  'sfdoctrinegeneratemigrationsmodelstask' => '/var/www/reverse_geocoding.dev/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsModelsTask.class.php',
  'sfdoctrinegenerateadmintask' => '/var/www/reverse_geocoding.dev/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateAdminTask.class.php',
  'sfdoctrinegeneratemoduleforroutetask' => '/var/www/reverse_geocoding.dev/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleForRouteTask.class.php',
  'sfdoctrinedropdbtask' => '/var/www/reverse_geocoding.dev/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDropDbTask.class.php',
  'sfdoctrinebuilddbtask' => '/var/www/reverse_geocoding.dev/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildDbTask.class.php',
  'sfdoctrinebuildmodeltask' => '/var/www/reverse_geocoding.dev/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildModelTask.class.php',
  'sfdoctrinedataloadtask' => '/var/www/reverse_geocoding.dev/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataLoadTask.class.php',
  'sfdoctrinedatadumptask' => '/var/www/reverse_geocoding.dev/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataDumpTask.class.php',
  'sfwebdebugpaneldoctrine' => '/var/www/reverse_geocoding.dev/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/debug/sfWebDebugPanelDoctrine.class.php',
  'sfdoctrinecli' => '/var/www/reverse_geocoding.dev/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/cli/sfDoctrineCli.class.php',
  'sfformfilterdoctrine' => '/var/www/reverse_geocoding.dev/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/form/sfFormFilterDoctrine.class.php',
  'sfformdoctrine' => '/var/www/reverse_geocoding.dev/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/form/sfFormDoctrine.class.php',
  'sfdoctrineexception' => '/var/www/reverse_geocoding.dev/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/sfDoctrineException.class.php',
  'sfdoctrineformgenerator' => '/var/www/reverse_geocoding.dev/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormGenerator.class.php',
  'sfdoctrineformfiltergenerator' => '/var/www/reverse_geocoding.dev/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormFilterGenerator.class.php',
  'sfdoctrinecolumn' => '/var/www/reverse_geocoding.dev/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineColumn.class.php',
  'sfdoctrinegenerator' => '/var/www/reverse_geocoding.dev/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineGenerator.class.php',
  'sftesterdoctrine' => '/var/www/reverse_geocoding.dev/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/test/sfTesterDoctrine.class.php',
  'sfdoctrineroutecollection' => '/var/www/reverse_geocoding.dev/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRouteCollection.class.php',
  'sfdoctrineroute' => '/var/www/reverse_geocoding.dev/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRoute.class.php',
  'swift_doctrinespool' => '/var/www/reverse_geocoding.dev/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/mailer/Swift_DoctrineSpool.class.php',
  'sfdoctrinerecord' => '/var/www/reverse_geocoding.dev/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecord.class.php',
  'sfdoctrinerecordi18nfilter' => '/var/www/reverse_geocoding.dev/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecordI18nFilter.class.php',
  'sfwidgetformdoctrinechoice' => '/var/www/reverse_geocoding.dev/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/widget/sfWidgetFormDoctrineChoice.class.php',
  'sfdoctrinepager' => '/var/www/reverse_geocoding.dev/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/pager/sfDoctrinePager.class.php',
  'sfvalidatordoctrinechoice' => '/var/www/reverse_geocoding.dev/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineChoice.class.php',
  'sfvalidatordoctrineunique' => '/var/www/reverse_geocoding.dev/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineUnique.class.php',

  // project
  'baseform' => '/var/www/reverse_geocoding.dev/lib/form/BaseForm.class.php',
  'userform' => '/var/www/reverse_geocoding.dev/lib/form/doctrine/TokenAuthPlugin/UserForm.class.php',
  'historyform' => '/var/www/reverse_geocoding.dev/lib/form/doctrine/TokenAuthPlugin/HistoryForm.class.php',
  'basehistoryform' => '/var/www/reverse_geocoding.dev/lib/form/doctrine/TokenAuthPlugin/base/BaseHistoryForm.class.php',
  'baseuserform' => '/var/www/reverse_geocoding.dev/lib/form/doctrine/TokenAuthPlugin/base/BaseUserForm.class.php',
  'baseformdoctrine' => '/var/www/reverse_geocoding.dev/lib/form/doctrine/BaseFormDoctrine.class.php',
  'baseformfilterdoctrine' => '/var/www/reverse_geocoding.dev/lib/filter/doctrine/BaseFormFilterDoctrine.class.php',
  'historyformfilter' => '/var/www/reverse_geocoding.dev/lib/filter/doctrine/TokenAuthPlugin/HistoryFormFilter.class.php',
  'userformfilter' => '/var/www/reverse_geocoding.dev/lib/filter/doctrine/TokenAuthPlugin/UserFormFilter.class.php',
  'baseuserformfilter' => '/var/www/reverse_geocoding.dev/lib/filter/doctrine/TokenAuthPlugin/base/BaseUserFormFilter.class.php',
  'basehistoryformfilter' => '/var/www/reverse_geocoding.dev/lib/filter/doctrine/TokenAuthPlugin/base/BaseHistoryFormFilter.class.php',
  'addhistory' => '/var/www/reverse_geocoding.dev/lib/migration/doctrine/1468759645_addhistory.php',
  'adduser' => '/var/www/reverse_geocoding.dev/lib/migration/doctrine/1468759646_adduser.php',
  'addfks' => '/var/www/reverse_geocoding.dev/lib/migration/doctrine/1468759647_addfks.php',

  // project_model
  'history' => '/var/www/reverse_geocoding.dev/lib/model/doctrine/TokenAuthPlugin/History.class.php',
  'historytable' => '/var/www/reverse_geocoding.dev/lib/model/doctrine/TokenAuthPlugin/HistoryTable.class.php',
  'usertable' => '/var/www/reverse_geocoding.dev/lib/model/doctrine/TokenAuthPlugin/UserTable.class.php',
  'basehistory' => '/var/www/reverse_geocoding.dev/lib/model/doctrine/TokenAuthPlugin/base/BaseHistory.class.php',
  'baseuser' => '/var/www/reverse_geocoding.dev/lib/model/doctrine/TokenAuthPlugin/base/BaseUser.class.php',
  'user' => '/var/www/reverse_geocoding.dev/lib/model/doctrine/TokenAuthPlugin/User.class.php',

  // application
  'myuser' => '/var/www/reverse_geocoding.dev/apps/geocodingAPI/lib/myUser.class.php',

  // modules
);
