<?php

/**
 * BaseUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $email
 * @property string $auth_token
 * @property Doctrine_Collection $History
 * 
 * @method string              getEmail()      Returns the current record's "email" value
 * @method string              getAuthToken()  Returns the current record's "auth_token" value
 * @method Doctrine_Collection getHistory()    Returns the current record's "History" collection
 * @method User                setEmail()      Sets the current record's "email" value
 * @method User                setAuthToken()  Sets the current record's "auth_token" value
 * @method User                setHistory()    Sets the current record's "History" collection
 * 
 * @package    reverse_geocoding
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUser extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user');
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('auth_token', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('History', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}