<?php

/**
 * BaseHistory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property string $message
 * @property User $User
 * 
 * @method integer getUserId()  Returns the current record's "user_id" value
 * @method string  getMessage() Returns the current record's "message" value
 * @method User    getUser()    Returns the current record's "User" value
 * @method History setUserId()  Sets the current record's "user_id" value
 * @method History setMessage() Sets the current record's "message" value
 * @method History setUser()    Sets the current record's "User" value
 * 
 * @package    reverse_geocoding
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseHistory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('history');
        $this->hasColumn('user_id', 'integer', 5, array(
             'type' => 'integer',
             'length' => 5,
             ));
        $this->hasColumn('message', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}