<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2016/07/17 21:19:17
sfConfig::add(array(
  'mod_tokenauthregister_enabled' => true,
  'mod_tokenauthregister_view_class' => 'sfPHP',
));
