<?php

/**
 * PluginUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginUserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginUser');
    }
    
    public function findOneByAccessToken($token){
        
         if (is_string($token) && strlen($token)>0){
            return $this->createQuery()
              ->where('auth_token = ?',$token)
              ->fetchOne();
            
        }else{
            return false;
        }
    }
}