<?php

/**
 * PluginHistoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginHistoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginHistoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginHistory');
    }
}